kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: stardelt
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./.kind-data/ozone
        containerPath: /var/lib/ozone
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30181
        hostPort: 8181
        protocol: TCP
